apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: informal-owl-go 
  janus-idp.io/tekton: informal-owl-go
  backstage.io/kubernetes-id: informal-owl-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: informal-owl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  