apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: informal-owl-go-gitops
  description: This is GitOps manifest for informal-owl-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: informal-owl-go
    janus-idp.io/tekton: informal-owl-go 
    backstage.io/kubernetes-id: informal-owl-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:informal-owl-go
